micronaut:
  application:
    name: carros
datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/carros?createDatabaseIfNotExist=true`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:diasz}
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: update
